root: true
extends:
  - next/core-web-vitals
  - plugin:tailwindcss/recommended
  - prettier
settings:
  tailwindcss:
    config: ./packages/website/tailwind.config.js
  next:
    rootDir: ./packages/website/
rules:
  no-restricted-imports:
    - error
    - paths:
        - name: lodash
        - name: next/image
      patterns:
        - group: [~/const/*]
        - group: [~/utils/*]
        - group: [~/types/*]
  '@next/next/no-img-element': 'off'
  import/order:
    - warn
    - groups:
        - [builtin, external]
        - internal
        - index
        - sibling
        - parent
        - type
        - object
      pathGroups:
        - pattern: ~/components/**
          group: internal
          position: before
        - pattern: ~/composables/**
          group: internal
          position: before
        - pattern: ~/constants
          group: internal
          position: before
        - pattern: ~/constants/**
          group: internal
          position: before
        - pattern: ~/enum
          group: internal
          position: before
        - pattern: ~/enum/**
          group: internal
          position: before
        - pattern: ~/utils
          group: internal
          position: before
        - pattern: ~/utils/**
          group: internal
          position: before
        - pattern: ~/config/**
          group: internal
          position: before
        - pattern: ~/types
          group: internal
          position: before
        - pattern: ~/types/**
          group: internal
          position: before
        - pattern: ~/**
          group: internal
          position: before
      alphabetize:
        order: asc
